# Generated by Django 5.0.3 on 2024-03-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_rename_destinations_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent')], default='CLIENT', max_length=100),
            preserve_default=False,
        ),
    ]
