# Generated by Django 5.0.3 on 2024-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(default='https://celemaifrumoasecapitale.wordpress.com/wp-content/uploads/2016/02/roma.jpg'),
            preserve_default=False,
        ),
    ]
