# Generated by Django 5.0.3 on 2024-03-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_destination_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
