# Generated by Django 5.0.3 on 2024-03-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_rename_image_url_destination_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='imageUrl',
            field=models.TextField(),
        ),
    ]
